### ISSUE TITLE
ng deploy doesn't work under windows

### ISSUE THREAD

**Issue by chrste90** [angular/angularfire#2101] opened 2019-06-03 06:38 UTC
This is an issue created for https://github.com/angular/angularfire2/issues/2086#issuecomment-497724706 as asked by @mgechev 

### Version info

**Angular:** 8.0.0

**Firebase:** 6.1.0

**AngularFire:** 5.2.0

**Angular CLI:** 8.0.0

### How to reproduce these conditions

**Steps to set up and reproduce**

Create a new CLI project under windows, run `ng add @angular/fire` and run `ng run deploy`.

### Debug output

```
ENOENT: no such file or directory, open '\C\Users\name\project\.firebaserc'
``` 

but the file exists and i can manually run `firebase deploy`.

### Expected behavior

Deployment of the application.

### Actual behavior

Error during deployment.

### Some debugging informations ###
I tried to find the source of the problem and it seems to come from https://github.com/angular/angularfire2/blob/8e5a99561fe35ff5705a4223b2b6b7406ec236ad/src/schematics/utils.ts#L59-L70

`projectRoot` under windows is starting with `/c/...` instead of `c:/...`. If i change the path to `c:/`, the deployment is working.

**Comment by Splaktar** [comment] 2019-07-21 04:43
This looks like a duplicate of https://github.com/angular/angularfire2/issues/2088.

**Comment by mgechev** [comment] 2019-07-21 04:56
Yes, let's close this issue and keep track in the one in AngularFire.

**Comment by NothingEverHappens** [comment] 2019-10-24 16:36
I finally have my windows laptop and going to look into this

**Comment by NothingEverHappens** [comment] 2019-10-24 16:51
Closing as a duplicate, going to look into the other issue.

**Closed by NothingEverHappens** 2019-10-24 16:51 UTC
