### ISSUE TITLE
Angular 13 with angular/fire 7.1.1

### ISSUE THREAD

**Issue by sfad** [angular/angularfire#3045] opened 2021-11-05 10:35 UTC
When I try to add @angular/fire to new project using ng add @angular/fire I end up with the following error:

npm ERR! While resolving: angular13@0.0.0
npm ERR! Found: @angular/common@13.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from @angular/fire@7.1.1
npm ERR! node_modules/@angular/fire
npm ERR!   @angular/fire@"7.1.1" from the root project

It seems like angular/fire not updated yet.

**Comment by xylo04** [comment] 2021-11-07 02:38
Probably a duplicate of #3044

**Closed** 2021-11-11 03:01 UTC
