### ISSUE TITLE
feat(redirectUnauthorizedTo): allow passing query parameters

### ISSUE THREAD

**Issue by AmitMY** [angular/angularfire#2287] opened 2020-01-15 10:50 UTC
### Version info

**Angular:**
~9.0.0-rc.7

**Firebase:**
^7.6.1-0

**AngularFire:**
^5.3.0-rc.4

Using the `AngularFireAuthGuard` works, but does not support redirect with query parameters.
When a user isn't authenticated, I'd like to direct them to login, and once they are logged in send them back to where they tried to access.

```ts
const redirectUnauthorizedToLogin = (route: ActivatedRouteSnapshot) => {
  const path = route.pathFromRoot.map(v => v.url.map(segment => segment.toString()).join('/')).join('/');
  const params = String(new URLSearchParams(route.queryParams));

  // const url = '/?' + String(new URLSearchParams({redirect: path + '?' + params}));

  return redirectUnauthorizedTo(['/']);
};
```

But I can't redirect to this url as its not a valid segment, and `redirectUnauthorizedTo` doesn't support query parameters

**Comment by jamesdaniels** [comment] 2020-02-06 10:02
Would allowing you to return your own `UrlTree` be sufficient?

**Comment by AmitMY** [comment] 2020-02-09 10:45
I believe it would be, yes.

For now, instead of using urls, i'm using:

```ts
const redirectUnauthorizedToLogin = (route: ActivatedRouteSnapshot) => {
  const path = route.pathFromRoot.map(v => v.url.map(segment => segment.toString()).join('/')).join('/');
  const params = route.queryParams;

  return pipe(
    loggedIn,
    tap((isLoggedIn) => {
      if (!isLoggedIn) {
        console.log('Saving afterLogin');
        sessionStorage.setItem('afterLogin', JSON.stringify({path, params}));
      }
    }),
    map(loggedIn => loggedIn || ['/'])
  );
};
```

**Comment by EdricChan03** [comment] 2020-05-09 09:12
Isn't this issue a duplicate of #2144?

**Comment by n0mer** [comment] 2020-07-09 21:11
@EdricChan03 any luck :) ?

**Closed** 2020-11-11 17:52 UTC
