### ISSUE TITLE
Package has unmet peer dependencies. Adding the package may not succeed.

### ISSUE THREAD

**Issue by kraftyman** [angular/angularfire#3587] opened 2024-12-09 23:34 UTC
Cannot install with the very latest Angular v.19.0.4 

Command failing: ng add @angular/fire@latest

Error received:

 Loading package information from registry
  › ‼ Package has unmet peer dependencies. Adding the package may not succeed.
√ Confirming installation
× Unable to install package

**Comment by jamesdaniels** [comment] 2024-12-12 21:23
Duplicate of #3581, working to support v19 now. In the meantime you can try our RC, `ng add @angular/fire@next`

**Closed by jamesdaniels** 2024-12-12 21:23 UTC

**Comment by kraftyman** [comment] 2024-12-12 21:29
Thank you all very much :)

**Comment by jattonio** [comment] 2024-12-21 02:49
> Duplicate of [#3581](https://github.com/angular/angularfire/issues/3581), working to support v19 now. In the meantime you can try our RC, `ng add @angular/fire@next`

Thank you, it works for me also.

**Comment by RyanP1978** [comment] 2025-05-29 15:36
> Cannot install with the very latest Angular v.19.0.4 
> 
> Command failing: ng add @angular/fire@latest
> 
> Error received:
> 
>  Loading package information from registry
>   › ‼ Package has unmet peer dependencies. Adding the package may not succeed.
- > ![readme.md](https://github.com/user-attachments/files/20507398/readme.md)

√ Confirming installation
> × Unable to install package
