### ISSUE TITLE
AngularFire, Google Auth Issue

### ISSUE THREAD

**Issue by samybaxy** [angular/angularfire#2172] opened 2019-09-16 16:34 UTC
Version info
Angular: 8.2.4

Firebase: 6.5.0

@angular/fire: 5.2.1

Other (e.g. Ionic/Cordova, Node, browser, operating system): Windows 10 Lenovo Yoga

I noticed that whenever I'm signed into my app using angularfire google authProvider: signInWithRedirect. I cannot seem to create a new document in an already existing collection using "add" on firebase firestore..
`this.firestore.collection('shopping-cart').add({ dateCreated: new Date().getTime() })`

But once I'm logged out, it works!
But as soon as I login again, same problem. I receive no data from the promise. I've tried catch as well, nothing returns.

One more thing - I've only tried this with the same google account which has access to the firebase console. I have no idea why this should even be a problem. 

Thank you.

**Comment by jamesdaniels** [comment] 2020-11-14 05:44
Unable to reproduce, probably addressed in recent versions.

**Closed by jamesdaniels** 2020-11-14 05:44 UTC
