### ISSUE TITLE
AngularFire v6 gives "Loading chunk 5 failed" on login on Google App Engine

### ISSUE THREAD

**Issue by aluedtke7** [angular/angularfire#2400] opened 2020-04-12 11:51 UTC
Hi,

I have a working web app made with Angular 9.1, AngularFire 5.3.0 and Firebase 6.4.2. The app uses also the Angular service-worker.
When I upgrade this app to Firebase 7.14.0 and AngularFire 6.0.0 (together with the neccessary source code changes), it works perfectly on localhost but when I deploy it to Google App Engine, I get the error message *Loading chunk 5 failed. (missing: https://my-private-web-app.ew.r.appspot.com/5.75932c0fb222721d6253.js)* on login.

So far, I figured out the following:
- the missing file is the firebase-auth js file which has a size of 172 kB
- in the debug network tab, I see this file is loaded as type **html** with a size of **963 bytes**
- later on, this file is loaded from the cache (963 bytes)
- the console is telling me, that this file was loaded, even though it's MIME-Type ("text/html") was wrong

The service-worker config file ngsw.json is listing the file `5.75932c0fb222721d6253.js` as a url in the `assetGroups` app with installMode = prefetch and updateMode = prefetch.
````
{
  "configVersion": 1,
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "/5.75932c0fb222721d6253.js",
        "/favicon.ico",
        "/index.html",
        "/main.ef5752c1f1ec119790fb.js",
        "/polyfills-es5.44cecd68bbc3d87f2802.js",
        "/polyfills.bdcacbb1b82cf7a67c27.js",
        "/runtime.c5813176b40d4d242a3d.js",
        "/styles.60c18df376267e2d6d8f.css"
      ],
      "patterns": []
      .....
````
When I compare the two dist/app folders (AngularFire 5.3.0 and 6.0.0), the only difference is an additional file `5.75932c0fb222721d6253.js` with AngularFire 6.0.0. The main.12345678900.js is roughly about the size of this file smaller than with AngularFire 5.3.0.

In mho the file is not loaded correctly due to the wrong MIME-Type. 

Am I wrong with my opinion?

### Version info
**Angular:** 9.1

**Firebase:** 7.14.0

**AngularFire:** 6.0.0

**Comment by jamesdaniels** [comment] 2020-11-18 19:20
Unable to reproduce with newer versions. Closing as outdated.

**Closed by jamesdaniels** 2020-11-18 19:20 UTC
