### ISSUE TITLE
Cannot find name 'PhoneOrOauthTokenResponse', 'UserInternal'

### ISSUE THREAD

**Issue by PR4SAN** [angular/angularfire#3217] opened 2022-05-07 10:35 UTC
### Version info

**Angular:** 13.2.0

**Firebase:** 

**AngularFire:** 7.3.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions
I followed the doc and initialized @angular/fire by ng add @angular/fire. and after that compiler is giving error.

### Debug output

** Errors in the JavaScript console **

Error: node_modules/@firebase/auth/dist/auth-public.d.ts:3137:22 - error TS2304: Cannot find name 'PhoneOrOauthTokenResponse'.

3137     _tokenResponse?: PhoneOrOauthTokenResponse;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/@firebase/auth/dist/auth-public.d.ts:3429:11 - error TS2304: Cannot find name 'UserInternal'.

3429     user: UserInternal;
               ~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✖ Failed to compile.

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
<img width="981" alt="Screenshot 2022-05-07 at 4 03 25 PM" src="https://user-images.githubusercontent.com/20751006/167250593-3a5e4343-ad6f-4938-84e9-3f8c9abd7b07.png">

**Comment by esk98** [comment] 2022-05-07 11:32
I have the same error. What could be missing when adding Firebase to a project?

**Comment by PR4SAN** [comment] 2022-05-07 11:47
> I have the same error. What could be missing when adding Firebase to a project?

No idea. i just created a demo project to check if anything in my project messing up with angular fire but same error with demo cli project

**Comment by esk98** [comment] 2022-05-07 11:50
I tried to find information about this error. There is nothing

**Comment by PR4SAN** [comment] 2022-05-07 12:18
> I tried to find information about this error. There is nothing

me too. if you find anything please answer here, i have to deliver the project now i am stuck in this.

**Comment by Farissabic** [comment] 2022-05-07 13:29
Is there any solution for this

**Comment by esk98** [comment] 2022-05-07 13:34
https://github.com/firebase/firebase-js-sdk/issues/6246
In this ticket there is something like a solution about @Internal, but it does not work for me

**Comment by imshm** [comment] 2022-05-07 13:36
> 

This will work after they will merge PR and push the release of a new version fix

**Comment by PR4SAN** [comment] 2022-05-07 13:50
> > 
> 
> This will work after they will merge PR and push the release of a new version fix

Any workaround for now? i tried with older versions still same issue

**Comment by Farissabic** [comment] 2022-05-07 14:29
I change both _tokenResponse and user to type any , and now it's working

**Comment by vandres** [comment] 2022-05-07 18:57
@PR4SAN Fixating Firebase to one version back fixed it for me. Maybe you need to clean your caches (e.g. node_modules)

**Comment by leo-guimaraes** [comment] 2022-05-07 20:21
As @vandres indicated, it also solved my problem. Now wait for the official fix that is already in the PR of the project.

**Comment by Micah-L18** [comment] 2022-05-07 22:38
got this to! 

i am at the very least happy that for once this is not my fault!

any update on fixes yet?

**Comment by robjvan** [comment] 2022-05-07 23:33
> @PR4SAN Fixating Firebase to one version back fixed it for me. Maybe you need to clean your caches (e.g. node_modules)

How do I roll back my Firebase version if I used `ng add @angular/fire` ?

**Comment by rlacatus** [comment] 2022-05-08 00:12
> > @PR4SAN Fixating Firebase to one version back fixed it for me. Maybe you need to clean your caches (e.g. node_modules)
> 
> How do I roll back my Firebase version if I used `ng add @angular/fire` ?

@robjvan - the issue is in the 'firebase' library, not '@angular/fire' - I made the same mistake at first.  Try:   `npm install firebase@9.7.0 --save --save-exact`.  That worked for me.

**Comment by JosaAyala** [comment] 2022-05-08 06:12
**This works for me!!!**


> > > @PR4SAN Fixating Firebase to one version back fixed it for me. Maybe you need to clean your caches (e.g. node_modules)
> > 
> > 
> > How do I roll back my Firebase version if I used `ng add @angular/fire` ?
> 
> @robjvan - the issue is in the 'firebase' library, not '@angular/fire' - I made the same mistake at first. Try: `npm install firebase@9.7.0 --save --save-exact`. That worked for me.

**Comment by robjvan** [comment] 2022-05-08 14:08
> **This works for me!!!**
> 
> > > > @PR4SAN Fixating Firebase to one version back fixed it for me. Maybe you need to clean your caches (e.g. node_modules)
> > > 
> > > 
> > > How do I roll back my Firebase version if I used `ng add @angular/fire` ?
> > 
> > 
> > @robjvan - the issue is in the 'firebase' library, not '@angular/fire' - I made the same mistake at first. Try: `npm install firebase@9.7.0 --save --save-exact`. That worked for me.

Awesome, thank you so much!!

**Comment by NorthFred** [comment] 2022-05-08 14:19
My project only uses the @angular/fire package without firebase whatsoever (I only use that authentication offered by angular fire). I have the same issue there.

I managed to get rid of the compilation error by downgrading eslint packages:

@eslint/eslintrc --> 1.2.2 (problem started on 1.2.3)

eslint --> 8.14.0 (problem started on 8.15.0)

**Comment by pam9708** [comment] 2022-05-08 18:00
Same issue here, changing version doesn't work, can anyone provide a fix for this ?

**Comment by Andresfelipemena93** [comment] 2022-05-08 23:55
> > > @PR4SANLa fijación de Firebase a una versión anterior lo arregló para mí. Tal vez necesite limpiar sus cachés (por ejemplo, node_modules)
> > 
> > 
> > ¿Cómo revertí mi versión de Firebase si usé `ng add @angular/fire`?
> 
> @robjvan- el problema está en la biblioteca 'firebase', no en '@angular/fire' - Cometí el mismo error al principio. Prueba: `npm install firebase@9.7.0 --save --save-exact`. Eso funcionó para mí.

Me funcionó, mil gracias.

**Comment by darknamer** [comment] 2022-05-09 00:20
I found something from dependency package in package.json

Test with 2 things is **_missing firebase_** package and use **_"firebase": "~9.7.0"_**
When I missing firebase package in package.json, nodejs will install package version 9.8.0 follow by picture

![image](https://user-images.githubusercontent.com/10751051/167321471-a2c88d55-1a94-47ed-9326-3b0f80bd9f79.png)

It has error with angular project

![image](https://user-images.githubusercontent.com/10751051/167321527-9ec263dd-d9b8-4d49-aacf-e4db894620a6.png)

In case use package firebase with ~9.7.0 is pass with easy game

![image](https://user-images.githubusercontent.com/10751051/167321587-6ffe32ab-5612-400a-85c5-4b9ef97e456b.png)

![image](https://user-images.githubusercontent.com/10751051/167321621-da209a20-7d81-47cd-abb9-7c372168c32c.png)

I think should check and fix dependency package in node_modules that use firebase 9.5.0-present (9.8.0) version has error with issue

**Comment by lifeoflikhon** [comment] 2022-05-11 11:13
Same error here. I am not using firebase directly. Using by @angular/fire. Then why I have to run `npm install firebase@9.7.0 --save --save-exact`?

**Comment by robjvan** [comment] 2022-05-11 11:22
> Same error here. I am not using firebase directly. Using by @angular/fire. Then why I have to run `npm install firebase@9.7.0 --save --save-exact`?

$angular/fire is a library to simplify working with Firebase services in an Angular app while the `firebase` package itself is a foundational library used by any of the Firebase services.  It's required for auth **or** firestore **or** analytics **or** realtime db, etc.  If you look under the dependencies of @angular/fire in github, you'll see it actually relies on `firebase` and many others

I think Firebase is in the middle of some sort of upgrade/transition and it's just a bad time to be caught between docs that haven't been updated and new methods that aren't properly documented yet.  You'll notice the AngularFire docs reference deprecated methods, so you need to the Firebase docs but this can take some interpreting

**Closed** 2022-08-18 16:24 UTC
