### ISSUE TITLE
collection.onSnapshotChanges() fires with outdated data

### ISSUE THREAD

**Issue by rulamon** [angular/angularfire#2660] opened 2020-11-17 10:20 UTC
### Version info

**Angular: 11.0.0**

**Firebase: 8.0.2**

**AngularFire: 6.1.0-rc.3**

### How to reproduce these conditions

https://stackblitz.com/edit/angular-ivy-izcnu6?file=src/app/app.component.ts

When clicking the button, each doc from the collection gets updated with a new 'number' value that's one higher than the previous. Check the console for the data coming in from snapshotChanges.

### Expected behavior

After updating the data in the docs of a collection, snapshotChanges should fire with the new data.

### Actual behavior

SnapshotChanges fires with the data from before the update, even though the update to cloud firestore succeeded, as proved with the data returned by a normal get.

**Comment by jamesdaniels** [comment] 2020-11-17 17:09
This appears to be a regression with Firebase `8.0.2`, roll back to `8.0.1` to get the correct behavior. See https://github.com/firebase/firebase-js-sdk/issues/4071

**Comment by jamesdaniels** [comment] 2020-11-17 17:11
Closing and pinning since it's a JS SDK issue that's being worked on. Work-around noted above.

**Closed by jamesdaniels** 2020-11-17 17:11 UTC
