### ISSUE TITLE
AngularFire router guards redirectUnauthorizedTo not working with ng build --prod

### ISSUE THREAD

**Issue by anisabboud** [angular/angularfire#2114] opened 2019-06-15 21:28 UTC
### Version info

**Angular:** `8.0.1`
**Firebase:** `6.2.0`
**AngularFire:** `5.2.1`
tsconfig.json `"target": "es5"`

### Steps to set up and reproduce

- Setup a Firebase project with auth router guards https://github.com/angular/angularfire2/blob/master/docs/auth/router-guards.md and https://github.com/RaphaelJenni/FirebaseUI-Angular
- Use `...canActivate(redirectUnauthorizedTo(['login']))` like below:
```
const appRoutes: Routes = [
  {
    path: '',
    ...canActivate(redirectUnauthorizedTo(['login'])),
    children: [
      { path: 'calendar', component: CalendarComponent },
      { path: '',
        redirectTo: 'calendar',
        pathMatch: 'full'
      },
    ],
  },
  {
    path: 'login',
    component: LoginComponent,
    ...canActivate(redirectLoggedInTo([''])),
  },
  { path: '**',
    redirectTo: '/',
    pathMatch: 'full'
  },
];
```
- Everything works great with `ng serve` or `ng build`, but with `ng build --prod`, the router guard `redirectUnauthorizedTo(['login'])` stops working. I.e., the user isn't redirected to /login, and can access the protected routes without logging in.

### Debug output

There are no errors in the console. The redirection just doesn't occur.
Using `RouterModule.forRoot(appRoutes, { enableTracing: true }),` confirms that.

With `ng build` (redirection to /login works): 
![image](https://user-images.githubusercontent.com/5672108/59556532-b12b0e00-8fcc-11e9-8ec6-75b0f99e4db8.png)

With `ng build --prod`: 
![image](https://user-images.githubusercontent.com/5672108/59556535-b4be9500-8fcc-11e9-8753-b65f4c90d905.png)

Notice that logging the AngularFireAuth.user observable (in yellow) shows that in the first case, it evaluated to null before the routing ended so the guard worked properly.
However, in the second case, the routing was performed before the auth state was evaluated (the observable hasn't emitted), and the guard didn't wait for it so it didn't work.

### Expected behavior

Route guards should work with `ng build --prod`.

### Actual behavior

Route guards work with `ng build` but not with `ng build --prod`.

**Comment by JGSolutions** [comment] 2019-06-16 02:16
For me I can't even get close as i get these errors. Then again I am lazy loading my modules

`ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[AngularFireAuthGuard]: 
  StaticInjectorError(Platform: core)[AngularFireAuthGuard]: 
    NullInjectorError: No provider for AngularFireAuthGuard!
NullInjectorError: StaticInjectorError(AppModule)[AngularFireAuthGuard]: 
  StaticInjectorError(Platform: core)[AngularFireAuthGuard]: 
    NullInjectorError: No provider for AngularFireAuthGuard!`

**Comment by Tyldar** [comment] 2019-06-16 11:50
@JGSolutions just add it in the providers of your app.module.ts, like a normal guard

**Comment by JGSolutions** [comment] 2019-06-17 14:39
@Tyldar Thanks it works

**Comment by ArrowsOff** [comment] 2019-06-19 20:17
> For me I can't even get close as i get these errors. Then again I am lazy loading my modules
> 
> `ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[AngularFireAuthGuard]: StaticInjectorError(Platform: core)[AngularFireAuthGuard]: NullInjectorError: No provider for AngularFireAuthGuard! NullInjectorError: StaticInjectorError(AppModule)[AngularFireAuthGuard]: StaticInjectorError(Platform: core)[AngularFireAuthGuard]: NullInjectorError: No provider for AngularFireAuthGuard!`

You should add `AngularFireAuthGuardModule` to your imports for the correct importing.

@anisabboud I came here with the same issue, seems like something is not working when minified.

**Comment by javanese84** [comment] 2019-06-20 21:12
Same issue here, works like it should with ng serve and after ng build --prod all routes are accessible. Is there a solution for this?

**Comment by ajheunis** [comment] 2019-06-22 03:47
Yup I have the same issue as @anisabboud. Works perfectly in other circumstances, but on a production build the AuthGuards don't run. Also tried with a custom guard with the same result. Thank you.

**Comment by sasa95** [comment] 2019-06-22 16:50
Same issue here.

**Comment by javanese84** [comment] 2019-06-26 19:51
Are there any news about this? This is currently a showstopper in my project :-(

**Comment by helloejsulit** [comment] 2019-06-28 06:58
Still waiting for a fix for this.

**Comment by F3LENYR** [comment] 2019-07-01 11:47
I have the same problem, I just want a auth guard like : 
```
import { AngularFireAuthGuard, loggedIn, redirectLoggedInTo } from '@angular/fire/auth-guard';

const redirectLoggedInToHome = redirectLoggedInTo(['/']);

const routes: Routes = [
  { path: '', component: HomeComponent },
  // { path: 'search', component: SearchComponent },
  // { path: 'search:query', component: SearchComponent },
  { path: 'login', component: LoginComponent, canActivate: [AngularFireAuthGuard], data: { authGuardPipe: redirectLoggedInToHome }},
  { path: 'register', component: RegisterComponent, canActivate: [AngularFireAuthGuard], data: { authGuardPipe: redirectLoggedInToHome }},
  { path: 'my-account', component: AccountComponent, canActivate: [AngularFireAuthGuard], data: { authGuardPipe: loggedIn }},
  { path: 'events', component: EventsComponent },`
];
```

but have this when i'm logged in and I try to go in '/login' for example : 
![dczqdzq](https://user-images.githubusercontent.com/24377043/60433891-2837e780-9c06-11e9-8f83-07ac3af8eb3f.PNG)

**Comment by devinshoemaker** [comment] 2019-07-03 01:16
The solution posted in issue #2099 works for me in production and non-production mode.

https://github.com/angular/angularfire2/issues/2099#issuecomment-503403712

**Comment by helloejsulit** [comment] 2019-07-03 04:38
I can confirm the solution in #2099 works for me too. Thanks for sharing @devinshoemaker!

**Comment by epicquestgames** [comment] 2019-07-14 10:37
Is there gonna be proper fix ?

**Comment by natrixnatrix89** [comment] 2019-08-07 10:31
Waiting for a proper fix too.

**Comment by MrBandaruk** [comment] 2019-08-10 16:38
Same problem here. the solution in #2099 works for me but how can I make it works for `redirectLoggedInTo`?

**Comment by aditi-enforce** [comment] 2019-08-29 06:05
Faced same problem. #2099 solution worked for me..
Can you please update https://github.com/angular/angularfire2/blob/master/docs/auth/router-guards.md documentation with this issue detail so other developers can make decision accordingly.

**Comment by benbabics** [comment] 2020-01-15 19:25
Despite adding `AngularFireAuthGuard` and `AngularFireAuthGuardModule` to *app.module.ts*, I am encountering the *NullInjectorError* but this time because there isn't a provider for `Router`, despite the fact that I am importing `RouterModule` in there as well!

```
errors.ts:30 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[AngularFireAuthGuard -> Router]: 
  StaticInjectorError(Platform: core)[AngularFireAuthGuard -> Router]: 
    NullInjectorError: No provider for Router!
NullInjectorError: StaticInjectorError(AppModule)[AngularFireAuthGuard -> Router]: 
  StaticInjectorError(Platform: core)[AngularFireAuthGuard -> Router]: 
    NullInjectorError: No provider for Router!
```

**Comment by Gbuomprisco** [comment] 2020-01-26 12:21
I am experiencing a similar issue as @benbabics, but only with SSR. 

Here's the stack trace:

```
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(HomePageModule)[AngularFireAuthGuard -> Router -> Router -> Router -> Router]: 
  NullInjectorError: No provider for Router!
NullInjectorError: R3InjectorError(HomePageModule)[AngularFireAuthGuard -> Router -> Router -> Router -> Router]: 
  NullInjectorError: No provider for Router!
```

**Comment by jpelton-stroud** [comment] 2020-02-11 17:27
> You should add `AngularFireAuthGuardModule` to your imports for the correct importing.

Thanks to @ArrowsOff for this tip; didn't realize AuthGuard was its own module; importing in root resolved the `NullInjectorError`, but then I was hit w/ the `source.lift is not a function` issue Id'd in #2099, resolved by [these](https://github.com/angular/angularfire/issues/2099#issuecomment-575976271) [two](https://github.com/angular/angularfire/issues/2099#issuecomment-575978633) posts in that thread.

Sure would be nice if this were documented...

**Comment by jenskragelund** [comment] 2020-02-26 08:24
I am experiencing the exact same issue as @benbabics when running my project on StackBlitz. However, when serving the same project on my desktop everything seems to work fine 😕

**Comment by harshal6094** [comment] 2020-04-24 10:47
> @JGSolutions just add it in the providers of your app.module.ts, like a normal guard

that also worked for me.

**Closed** 2020-11-18 18:29 UTC
