### ISSUE TITLE
Firebase Function not working

### ISSUE THREAD

**Issue by alekcey0211** [angular/angularfire#2456] opened 2020-05-16 13:41 UTC
Why my component dont render data from functions? but console.log() show returned value?
async pipe dont render the value from functions,,,
``` typescript
import { BrowserModule } from "@angular/platform-browser";
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";
...
import { environment } from "../environments/environment";

import { AngularFireModule } from "@angular/fire";
import { AngularFirestoreModule } from "@angular/fire/firestore";
import { AngularFireFunctionsModule } from '@angular/fire/functions';
import { ExamplesFirebaseFunctionsComponent } from './examples/firebase-functions.component';

@NgModule({
  declarations: [
    ...
    ExamplesFirebaseFunctionsComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    ...
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule,
    AngularFireFunctionsModule,
    ...
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppModule {}

```
``` typescript
import { Component } from "@angular/core";
import { AngularFireFunctions } from "@angular/fire/functions";
import { map } from 'rxjs/operators';

@Component({
  selector: "examples-firebase-functions",
  template: `
    <h1>FireBase Functions Example</h1>
    <pre>{{ data$ | async }}</pre>
  `,
})
export class ExamplesFirebaseFunctionsComponent {
  data$;
  constructor(private fns: AngularFireFunctions) {
    const callable = fns.httpsCallable("transpon");
    this.data$ = callable({ songId: "170180" }).pipe(
      map((text: any) => {
        console.log(text.transformed); // return value
        return "test";
      })
    );
  }
}
```

**Comment by crtl** [comment] 2020-05-18 13:34
Duplicate of  #2452

**Comment by jamesdaniels** [comment] 2020-11-13 01:23
Zone issues have been patched in affunctions.

**Closed by jamesdaniels** 2020-11-13 01:23 UTC
