### ISSUE TITLE
App Check and Authentication issue

### ISSUE THREAD

**Issue by im12345dev** [angular/angularfire#3456] opened 2023-11-04 23:50 UTC
Hey guys,

As it seems App Check is not working with the authentication model, it's not sending any token with the authentication requests resulting in app check failure every time.

App Check tokens seems to work fine with Firestore and Storage models.

**Comment by Sapython** [comment] 2023-11-06 05:05
Can you provide some code that you have tried. As already mentioned by @google-oss-bot you are not following the issue template. Please do so and I will help you out.

**Comment by Sapython** [comment] 2023-11-06 05:13
This seems to be a duplicate of https://github.com/angular/angularfire/issues/3427 If it does then please close this issue and continue the discussion over there.

**Closed** 2023-11-10 16:46 UTC
