### ISSUE TITLE
add angular v17 support

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angularfire#3459] opened 2023-11-08 19:16 UTC
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by DimitriTsikaridze** [comment] 2023-11-09 03:33
maybe but I'm currently having issues where when I run ng add in v17 angular/fire it doesn't find compatible package

**Comment by Hambat** [comment] 2023-11-11 11:00
any news?

**Comment by nolansingroy** [comment] 2023-11-11 23:44
I am having same issues. I created a angular project in 17 but adding angular fire does not support schematics 

 ng add @angular/fire
Skipping installation: Package already installed
Package "@angular/fire" was found but does not support schematics.

**Comment by rpaivabr** [comment] 2023-11-13 12:15
+1

**Comment by DimitriTsikaridze** [comment] 2023-11-13 19:29
> Is there a way to ignore the conflicting dependency until we get the release 17?

maybe with legacy peer deps or force or both, I haven't tried yet

**Comment by gazz9ar** [comment] 2023-11-13 19:38
> > Is there a way to ignore the conflicting dependency until we get the release 17?
> 
> maybe with legacy peer deps or force or both, I haven't tried yet

I run npm i --legacy-peer-deps and the login I had with firebase still works

**Comment by PierreDuc** [comment] 2023-11-14 15:35
For me it worked to just do `ng add @angular/fire@next`. But this was with a new project

**Comment by lorenzbaum** [comment] 2023-11-16 13:20
A working v17 would be fantastic, as with `@next` the deployment does not work (jet):

With `ng build` and the new builder (`@angular-devkit/build-angular:application`) now creating subfolders for `browser` and eventually `server`, Firebase uploads it including those folders, rendering the Angular web app corrupted.

**Comment by sergiotome** [comment] 2023-11-27 10:24
any update on this? @jamesdaniels , can we at least get a tentative date on when a final version for v17 could be ready?

**Comment by dolanmiu** [comment] 2023-12-03 18:59
Considering `@angular/fire@16.0.0` was released 2 months ago, I have a feeling think 17 won't be released until a while longer lol (I really hope I am wrong)

**Comment by DimitriTsikaridze** [comment] 2023-12-10 14:20
I think normal SPA app would work fine, I'm have angular with ssr enabled, previously I used it only as SSG, I didn't want to pay for server so I built my routes during build time, however now when I do ng deploy I get 'firebase deploy error, Error: Failed to list functions for (project name)' error when I don't use functions, is there any option to disable full ssr yet? I only want SSG

**Comment by adamgasiorek** [comment] 2023-12-11 13:27
For me update doesnt work i have following error:
`require() of ES Module /Users/adamg/WebstormProjects/testng/node_modules/inquirer/lib/prompts/base.js from /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js not supported.
Instead change the require of base.js in /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js to a dynamic import() which is available in all CommonJS modules.`

**Comment by DenysRakhuba** [comment] 2024-01-17 09:31
Hello,
Any updates on this? Does it work already with Angular 17 without issues? I'm asking because the issue is still "Open"

**Comment by onyet** [comment] 2024-04-01 09:41
> For me update doesnt work i have following error: `require() of ES Module /Users/adamg/WebstormProjects/testng/node_modules/inquirer/lib/prompts/base.js from /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js not supported. Instead change the require of base.js in /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js to a dynamic import() which is available in all CommonJS modules.`

I have the same problem.

**Comment by ohabash** [comment] 2024-04-11 18:30
> For me update doesnt work i have following error: `require() of ES Module /Users/adamg/WebstormProjects/testng/node_modules/inquirer/lib/prompts/base.js from /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js not supported. Instead change the require of base.js in /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js to a dynamic import() which is available in all CommonJS modules.`

same

**Comment by rafazf** [comment] 2024-04-30 16:35
> Para mí la actualización no funciona, tengo el siguiente error: `require() of ES Module /Users/adamg/WebstormProjects/testng/node_modules/inquirer/lib/prompts/base.js from /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js not supported. Instead change the require of base.js in /Users/adamg/WebstormProjects/testng/node_modules/inquirer-autocomplete-prompt/index.js to a dynamic import() which is available in all CommonJS modules.`

Alguna solucion? tengo el mismo error

**Comment by askeric** [comment] 2024-05-11 17:23
Hi @DimitriTsikaridze .. what was the resolution for close? Fixed, dupe, won't fix, etc? I didn't see any recent checkins. Any other update? Ty!

**Comment by DimitriTsikaridze** [comment] 2024-05-11 17:31
it just works now, I think after couple of updates error went away. currently using these versions and everything works.

```
 "dependencies": {
    "@angular/animations": "^17.2.0",
    "@angular/cdk": "^17.2.2",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
    "@angular/fire": "^17.0.1",
    "@angular/forms": "^17.2.0",
    "@angular/material": "^17.2.2",
    "@angular/platform-browser": "^17.2.0",
    "@angular/platform-browser-dynamic": "^17.2.0",
    "@angular/platform-server": "^17.2.0",
    "@angular/router": "^17.2.0",
    "@angular/ssr": "^17.2.2",
    "@ngneat/transloco": "^6.0.4",
    "express": "^4.18.2",
    "rxjs": "~7.8.0",
    "swiper": "^11.0.7",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
```

**Closed** 2024-05-11 17:31 UTC
