### ISSUE TITLE
subscribe is not working in the second time

### ISSUE THREAD

**Issue by SonuSahoo** [angular/angularfire#1892] opened 2018-09-21 12:31 UTC
Hi i am using firestore through angularfire2 i want to call a collection once the app loaded and want to store in a observable variable and want to use through out the app below is my code.

**in constructor** 
```
 fleets: Observable<Fleet[]>;
this.fleets =this.afs.collection('Fleets').snapshotChanges().pipe(map(
      changes => {
        return changes.map(
          a => {
            const data = a.payload.doc.data() as Fleet;
            data.id = a.payload.doc.id;
            return data;
          });
      }));

getflleet()
{
return this.fleets;
}
```

**in more than one component** 

```
this.firebaseService.getflleet()
     .subscribe(
       (fleet) => {
         this.arr = fleet;
         console.log(this.arr);
       }
     );
   }
```

but the problem is only once a time its calling in the first component.
Thanks in andvance

**Comment by kbala** [comment] 2018-10-05 14:36
Yes, it doesn't trigger for second time changes. Any help please....

**Comment by futuredayv** [comment] 2018-10-07 22:29
I started to learn about RxJS recently and I don't think it is an appropriate way to use Subjects like this but I am using Subjects on services to hold and serve data. [Not the best but surely works for me.](https://paste.ofcode.org/NKxtthSnvzqZX4WdR94JbR) It works when you revisit component because BehaviorSubject always have recently passed value.

**Comment by alberthoekstra** [comment] 2018-10-09 17:55
Indeed, a BehaviorSubject is what you wanna use.

**Comment by dalepo** [comment] 2018-12-16 22:20
I suggest using the `shareReplay` operator in this case.

**Comment by jamesdaniels** [comment] 2020-11-18 17:35
RXJS things. Working as intended. Closing.

**Closed by jamesdaniels** 2020-11-18 17:35 UTC
