### ISSUE TITLE
ERROR ReferenceError: Proxy is not defined

### ISSUE THREAD

**Issue by JeongJun-Lee** [angular/angularfire#2450] opened 2020-05-10 08:10 UTC
### Version info

**Angular:** Angular9

**Firebase:** Firebase 7.14.x

**AngularFire:** AngularFire6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic5, Cordova7, Capacitor2

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
1) Build Ionic Android App by Capacitor. 
2) Load tha App on real phone of Android 6, Chome 79
3) Happens Proxy is not defined error from new AngularFireAuth.
 

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **
![image](https://user-images.githubusercontent.com/11474775/81494008-92a5c380-92be-11ea-96f0-54317200dfe3.png)

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
It works well on Web App build by ionic serve.
It works well on real phone of Android 10.
So it need to work well on Android 6.

**Comment by rgant** [comment] 2020-05-14 16:58
Duplicate of #2296

**Comment by jamesdaniels** [comment] 2020-10-30 20:53
You'll want to polyfill proxy.

**Closed by jamesdaniels** 2020-10-30 20:53 UTC
