### ISSUE TITLE
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore

### ISSUE THREAD

**Issue by igoraugustynski** [angular/angularfire#3429] opened 2023-09-04 19:07 UTC
### Version info

**Angular:** 16.1.0

**Firebase:** ?

**AngularFire:** 7.6.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** None

### How to reproduce these conditions

`npm i @angular/fire`

```
import { inject, Injectable } from '@angular/core';
import { doc, Firestore, setDoc } from '@angular/fire/firestore';

(...)

createBooking(booking: Booking) {
    const bookingRef = doc(this.firestore, FirestoreCollections.Bookings, 
    booking.bookingData.email).withConverter(bookingConverter);
    return setDoc(bookingRef, booking);
}
```

**Steps to set up and reproduce**

I tried it without the `.withConverter()` function. Also tried reinstalling @angular/fire, removing node_modules etc.
FirestoreCollections is just an enum, `Bookings` value is `bookings`.

### Debug output
`FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore`

### Expected behavior

Should correctly set the document.

### Actual behavior

`FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore`

**Comment by Sapython** [comment] 2023-09-05 00:59
This is the duplicate of https://github.com/angular/angularfire/issues/3422

**Closed** 2023-09-05 06:58 UTC
