### ISSUE TITLE
signInWithRedirect does not redirect back to app

### ISSUE THREAD

**Issue by h2u** [angular/angularfire#1860] opened 2018-09-07 16:08 UTC
### Version info

Windows 10 64
Ionic 4
Cordova 8
Android 7 (26)

```
{
  "name": "appTest",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/fire": "^5.0.0",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.12.0",
    "@ionic-native/splash-screen": "~4.12.0",
    "@ionic-native/status-bar": "~4.12.0",
    "@ionic/storage": "2.1.3",
    "cordova-android": "7.0.0",
    "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-buildinfo": "^2.0.2",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-customurlscheme": "^4.3.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^2.1.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-universal-links-plugin": "^1.2.1",
    "firebase": "^5.4.2",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-buildinfo": {},
      "cordova-universal-links-plugin": {},
      "cordova-plugin-browsertab": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "io.ionic.starter",
        "ANDROID_SCHEME": " ",
        "ANDROID_HOST": " ",
        "ANDROID_PATHPREFIX": "/"
      }
    },
    "platforms": [
      "android"
    ]
  }
}
```

### How to reproduce these conditions

- start blank ionic project
- install & setup angularfire
- complete guide: https://firebase.google.com/docs/auth/web/cordova?authuser=2

home.ts
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { AngularFireAuth } from '@angular/fire/auth';
import { auth } from 'firebase';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(
    public navCtrl: NavController,
    public afAuth: AngularFireAuth
  ) {

  }

  login() {
    this.afAuth.auth.signInWithRedirect(new auth.GoogleAuthProvider()).then(() => {
      this.afAuth.auth.getRedirectResult().then(result => {
        console.log('auth result', result);
      }).catch(error => {
        console.log('auth error', error);
      });
    });
  }

  logout() {
    this.afAuth.auth.signOut();
  }

}
```

home.html
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
    <div *ngIf="afAuth.user | async as user; else showLogin">
      <h1>Hello {{ user.displayName }}!</h1>
      <button ion-button (click)="logout()">Logout</button>
    </div>
    <ng-template #showLogin>
      <p>Please login.</p>
      <button ion-button (click)="login()">Login with Google</button>
    </ng-template>
</ion-content>

```

### Debug output

Console is empty.
After i logged in on google accounts, it redirects me to here:

![whatsapp image 2018-09-07 at 20 06 18](https://user-images.githubusercontent.com/5619582/45230315-88f1de80-b2d9-11e8-8da7-f1346cb33b5b.jpeg)

### Expected behavior

Redirect to app

### Actual behavior

Stuck in browser

**Comment by codediodeio** [comment] 2018-09-10 04:30
I can confirm this issue as well, but have no idea how to debug.  It's not an issue with AF, which works fine with redirect auth on the web, so I'm assuming it's an issue in one of those cordova black boxes.  

 A workaround for Google Auth is to use the Google Plus Plugin and and use `signInWithCredential`. Here's a full guide verified with Ionic 4 https://angularfirebase.com/lessons/ionic-google-login-with-firebase-and-angularfire/

**Comment by h2u** [comment] 2018-09-10 14:37
Hey, @codediodeio . Thanks for reply. Tried today your solution but it's not working giving everytime error: Object(...) is not a function at GooglePlus.login (index.js:24)

Spent few hours of finding the solution, nothing helped, switched to another work :) Maybe you know something about this error?

**Comment by codediodeio** [comment] 2018-09-10 14:42
That error is usually related to RxJS, does `npm install rxjs-compat` fix it? (and restart your dev server)

**Comment by h2u** [comment] 2018-09-10 14:56
Just updated rxjs-compat, restarted server. Nothing changed.

```
TypeError: Object(...) is not a function
    at GooglePlus.login (index.js:24)
    at AppProvider.<anonymous> (app.provider.ts:37)
    at step (main.ts:5)
    at Object.next (main.ts:5)
    at main.ts:5
    at new t (polyfills.js:3)
    at webpackJsonp.37.__awaiter (main.ts:5)
    at AppProvider.webpackJsonp.37.AppProvider.nativeGoogleLogin (app.provider.ts:34)
    at AppProvider.webpackJsonp.37.AppProvider.doGoogleLogin (app.provider.ts:75)
    at Object.eval [as handleEvent] (WelcomePage.html:10)
```

**Comment by codediodeio** [comment] 2018-09-10 15:35
If you're on Ionic v3 you want `npm i @ionic-native/google-plus@4.12.2` and  the import should look like

```
import { GooglePlus } from '@ionic-native/google-plus'
```

On Ionic v4, you need all native plugins updated to 5.0.0-beta and imported from npx. 

```
import { GooglePlus } from '@ionic-native/google-plus/npx'
```

**Comment by h2u** [comment] 2018-09-10 15:54
Im on v4 and imports are as you say.

**Comment by codediodeio** [comment] 2018-09-10 16:14
Are you sure,  v4 should have `"@ionic/angular": "^4.0.0-beta"`, but the package on this issue is `"ionic-angular": "3.9.2"`

**Comment by h2u** [comment] 2018-09-11 06:15
I thought @ionic-native/core is ionic version and it's 4.12.2, and there is no package @ionic/angular, only ionic-angular and the latest version is 4.0.0-alpha.0 not 4.0.0-beta. You sure that i need to update ionic-angular?

**Comment by h2u** [comment] 2018-09-11 06:17
Ok, i found package - https://www.npmjs.com/package/@ionic/angular
Do i need to remove ionic-angular then?

**Comment by h2u** [comment] 2018-09-11 06:51
Okay, everything works now. I did not installed @ionic/angular. Downgraded @ionic-native/google-plus to 4.12.2 and it's working now. Thank you.

**Comment by raphrmx** [comment] 2019-01-25 08:37
Hello,

I also encounter this problem since switching to ionic V4 and its latest plugin "cordova-plugin-ionic-webview" without finding an alternative.
I wish I could connect with other social networks (Facebook, Twiter, etc.)
If I understand correctly the problem comes from an ionic webview compatibility issue that uses an internal web server.

Do you plan to patch this to make it compatible with this one?

Thank you in advance for your responsiveness :)

**Comment by raphrmx** [comment] 2019-01-25 08:38
Hello,

I also encounter this problem since switching to ionic V4 and its latest plugin "cordova-plugin-ionic-webview" without finding an alternative.
I wish I could connect with other social networks (Facebook, Twiter, etc.)
If I understand correctly the problem comes from an ionic webview compatibility issue that uses an internal web server.

Do you plan to patch this to make it compatible with this one?

Thank you in advance for your responsiveness :)

**Comment by ngrealish** [comment] 2019-02-03 19:41
I'm also having an issue with this.  Both signInWithRedirect and signInWithPopUp don't work.  When I use redirect, I get the exact same issue as above with the same alert boxes.  I have everything upgraded

```
"dependencies": {
    "@angular/common": "6.0.9",
    "@angular/core": "6.0.9",
    "@angular/fire": "^5.1.1",
    "@angular/forms": "6.0.9",
    "@angular/http": "6.0.9",
    "@angular/platform-browser": "6.0.9",
    "@angular/platform-browser-dynamic": "6.0.9",
    "@angular/router": "6.0.9",
    "@ionic-native/core": "5.0.0-beta.14",
    "@ionic-native/splash-screen": "5.0.0-beta.14",
    "@ionic-native/status-bar": "5.0.0-beta.14",
    "@ionic/angular": "4.0.0-beta.0",
    "@ionic/ng-toolkit": "1.0.0",
    "@ionic/schematics-angular": "1.0.0",
    "angularfire2": "^5.0.0-rc.11",
    "cordova-android": "7.1.4",
    "cordova-browser": "^5.0.4",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-ionic": "^5.2.10",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.3",
    "dragula": "^3.7.2",
    "firebase": "^5.7.3",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "moment": "^2.22.2",
    "rxjs": "6.2.2",
    "zone.js": "^0.8.26"
  },
```

**Comment by murat0** [comment] 2019-04-10 10:50
Anyone still experiencing this issue

- add <allow-navigation href="*"/> into your config

**Comment by FOStack** [comment] 2019-09-26 17:42
And add `<preference name="OverrideUserAgent" value="Mozilla/5.0 Google" />` if you run into unauthorized user agent error screen

**Comment by saoud77** [comment] 2019-10-12 09:45
It worked with me when I downgrade ios platform to 4.5.4

**First**: you need to remove the current ios platform:
cordova platform rm ios

**Second**: add ios platform version 4.5.4
cordova platform add ios@4.5.4

**Comment by curiouscod3** [comment] 2020-07-19 07:37
I think it is better to use Native method...with Capacitor

**Comment by jamesdaniels** [comment] 2020-11-18 17:38
Closing as there are work arounds and this isn't AF specific.

**Closed by jamesdaniels** 2020-11-18 17:38 UTC
