### ISSUE TITLE
GCP Token keeps refreshing when local time is incorrect

### ISSUE THREAD

**Issue by willemjanvankranenburg** [angular/angularfire#2621] opened 2020-10-27 13:53 UTC
### Version info

**Angular:** 10.1.0

**Firebase:** 7.19.1

**AngularFire:** 6.0.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Node: 12.18.4

### How to reproduce these conditions

**Steps to set up and reproduce**

1. Clone this AngularFire project.
2. Open AngularFire project in an editor.
2.1. Open the package.json in /sample, and change the version of `@angular/fire` to the most recent version (6.0.3).
3. `cd <project_location>/sample` in cmd.
4. `npm i`.
5. In 'environment.ts, change the firebase config to your own project.
6. In 'auth.component.ts' change `this.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider());` to `this.auth.signInWithEmailAndPassword('email', 'password');` (with existing credentials from your firebase project).
7. ng serve.
8. In a browser goto localhost:4200 -> click sign in button.
9. Open developer tools (F12) -> goto network tab.
10. Press F5, every call seems fine, and after a second or 2 it stops doing network calls.
11. Change the time on your local computer to at least an hour in the future.
12. Go back to your browser, and press F5 again (with the network tab in the developer tools open).
13. Observe a lot of calls to https://securetoken.googleapis.com/v1/token?key=<TOKEN>. After a short while the resonse will be 400, timeout.

**Sample data and security rules**
A "fresh" firebase project with 1 user and only hosting enabled.

### Debug output
![image](https://user-images.githubusercontent.com/31033654/97310570-a987a480-1863-11eb-8406-b2fb970224fa.png)

### Expected behavior
The expected behavior is that the token is only retrieved once, and after an hour is passed the token will be refreshed, just like when the time on your computer is the correct time.

### Actual behavior
The actual behavior is that when the local time on your computer is more than an hour in the future, the token will be refreshed constantly until google "forces" it to stop, by sending a 400.

This behavior only happens when using angularFire to handle the auth. When only using firebase, it doesn't happen.

**Comment by willemjanvankranenburg** [comment] 2020-11-03 08:25
Anybody else experiencing this problem?

**Comment by akshaybabloo** [comment] 2020-11-05 19:47
Are you running this locally or on production server? Because I can try to change the time on my system and try to reproduce it

**Comment by willemjanvankranenburg** [comment] 2020-11-06 07:24
It happens both locally and on a production server. Like I mentiond in the post, the easiest way to reproduce this, is to check out the samples in this project, change the sign in way to `signInWithEmailPassword` and put the time of your system to more than an hour in the future. It always happens to me and my colleagues..

**Comment by basvandenheuvel** [comment] 2020-11-13 13:05
I'm having the exact same issue. 

It seems that the issue does not appear when using firebase directly.

**Comment by willemjanvankranenburg** [comment] 2020-11-19 10:40
Even with the newest version of firebase (8.0.2) and the newest version of @angular/fire (6.1.1) it keeps happening.

@akshaybabloo Have you tried to reproduce it? And what are your findings?

**Comment by akshaybabloo** [comment] 2020-11-19 23:26
I don't seem to have this issue. Are you using the auth emulator?

**Comment by nikoswsn** [comment] 2021-04-09 15:32
Hi @jamesdaniels, any official update on this?

I've encountered this issue in two different days in production. Both these days we observed a spike in Firestore Read Operations.
Can someone confirm if the Firestore Listeners trigger every time the token refreshes and billing those reads even though the Token is considered expired?

**Comment by jamesdaniels** [comment] 2021-09-15 05:47
I've ben unable to reproduce, closing as we're moving to the new API. If I can get a simple repro that isolates it from the JS SDK I'm happy to look into it.

**Closed by jamesdaniels** 2021-09-15 05:47 UTC
Labels: type: bug, needs: investigation
