### ISSUE TITLE
limitToLast and 'child_added' do not work together

### ISSUE THREAD

**Issue by Maistho** [angular/angularfire#1773] opened 2018-07-07 19:06 UTC
### Version info

**Angular:** 6.0.7

**Firebase:** 5.2.0

**AngularFire:** 5.0.0-rc.11

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

See this stackblitz

https://stackblitz.com/edit/angular-nm6r3a?file=app%2Fapp.component.ts

**Steps to set up and reproduce**

```typescript
this.list$ = this.db.list(ref, ref => ref.limitToLast(1)).valueChanges(['child_added']);
```
When using limitToLast and 'child_added' the limit is not kept after the first item.

### Expected behavior
I should only get the latest added child

### Actual behavior
I get every child that is added since I first started the subscription

**Comment by Kamshak** [comment] 2018-07-11 18:03
i think you're looking for 

```this.list$ = this.db.list(ref).valueChanges(['child_added']).pipe(first());```

**Comment by Maistho** [comment] 2018-07-11 18:13
@Kamshak Yes, that's what I'm using, but the bug is that limitToLast should already limit to only the most recently added item.

The following code will probably work, but is a workaround that I shouldn't need.
```
this.list$ = this.db.list(ref, ref => ref.limitToLast(1)).valueChanges(['child_added']).pipe(last());
```

**Comment by Kamshak** [comment] 2018-07-11 20:07
Limit to last will give you the last highest priority item (unless you order by child or something else) i think. It does not mean give me only last added child (1 value). See also https://firebase.google.com/docs/database/admin/retrieve-data#limit-queries

```ts
var ref = db.ref("dinosaurs");
ref.orderByChild("weight").limitToLast(2).on("child_added", function(snapshot) {
  console.log(snapshot.key);
});
``` 
See the explanation:
> The child_added callback is triggered exactly two times, unless there are less than two dinosaurs 
> stored in the database. It will also get fired for every new, heavier dinosaur that gets added to the database

**Comment by Maistho** [comment] 2018-07-11 23:28
Thanks for a good explanation! 👍 

I still think that the behaviour is somewhat confusing though, since I get only the `n` most recent values when not only listening to `child_added`.

Maybe the Observable should not emit a list, and only emit values instead? I feel like my confusion is from getting a list with a bunch of `child_added` events instead of getting each child one by one. When I've gotten the first `child_added` event I will get that same event in the array every time a new child is added. 🤔 

What I'm after in the end is to have an Observable that emits any new children in the list, and that only gives me the most recent child when starting the subscription. Probably easier to just not use angularfire in that case:


```ts
const subject = new ReplaySubject<any>(1)
const ref = this.db.database.ref('/dinosaurs');
ref.limitToLast(1).on('child_added', snapshot => {
  this.ngZone.run(() => {
    subject.next(snapshot.val());
  });
});
```

**Comment by Kamshak** [comment] 2018-07-12 16:19
Yeah you're right that might be a bug, it seems that in the implementation of the list observable it always merges in a "value" change [1], even though "child_added" would be enough to fetch everything. Perhaps there is a reason for this, @davideast probably knows more.

[1] https://github.com/angular/angularfire2/blob/2c2fe021667b8675a6ceabb891f979c20d632570/src/database/list/changes.ts#L10

**Comment by davideast** [comment] 2018-07-30 18:13
@Kamshak Child added is not enough to fetch everything. We need to know what the "initial state" of the list. That way we only emit the array once the "initial state" is in place.

**Comment by jamesdaniels** [comment] 2020-11-18 17:45
closing as it seems this is working as intended for right now

**Closed by jamesdaniels** 2020-11-18 17:45 UTC
