### ISSUE TITLE
Warnings on  optimization bailouts when ng serve

### ISSUE THREAD

**Issue by cupidchan** [angular/angularfire#2565] opened 2020-08-06 13:53 UTC
### Version info

**Angular:**
10.0.1

**Firebase:**
8.6.0

**AngularFire:**
6.0.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

Whenever I try to ng server, i got the following warnings:

WARNING in /Users/cupidchan/Documents/GitHub/pistevo-health/web/node_modules/@angular/fire/__ivy_ngcc__/fesm2015/angular-fire.js depends on 'firebase/app'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/cupidchan/Documents/GitHub/pistevo-health/web/node_modules/@angular/fire/__ivy_ngcc__/fesm2015/angular-fire-firestore.js depends on '@firebase/app'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/cupidchan/Documents/GitHub/pistevo-health/web/node_modules/@angular/fire/__ivy_ngcc__/fesm2015/angular-fire-firestore.js depends on '@firebase/firestore'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/cupidchan/Documents/GitHub/pistevo-health/web/node_modules/@firebase/firestore/dist/index.cjs.js depends on '@firebase/component'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/cupidchan/Documents/GitHub/pistevo-health/web/node_modules/@firebase/firestore/dist/index.cjs.js depends on '@firebase/util'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

There shouldn't be a warning of optimization bailout

### Actual behavior

Warnings show optimization bailout

**Comment by Splaktar** [comment] 2020-08-12 01:50
Duplicate of https://github.com/angular/angularfire/issues/2478 and https://github.com/firebase/firebase-js-sdk/issues/3315.

**Comment by jamesdaniels** [comment] 2020-10-30 16:48
This is fixed in the latest major Firebase release, it will be supported in AF `6.0.4` which will be cut shortly.

**Closed by jamesdaniels** 2020-10-30 16:48 UTC

**Comment by pgg** [comment] 2020-10-30 21:02
> This is fixed in the latest major Firebase release, it will be supported in AF `6.0.4` which will be cut shortly.

in AF `6.0.4`: '@angular/fire/firestore'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by jamesdaniels** [comment] 2020-10-31 15:12
Not sure why that would be... `@angular/fire/firestore` like the rest of `@angular/fire` is compiled by the Angular CLI and most definitely conforms to AFP. 

@StephenFluin @mgechev any thoughts? Firebase v8 is modules now, AngularFire is compiled with ng cli and nothing obviously wrong in the `package.json`. CLI / ngcc is still complaining. 🤷

**Comment by StephenFluin** [comment] 2020-11-07 00:53
I'm not seeing these warnings anymore on the latest version of @angular/fire (6.0.4) and Firebase (8.0.1) and Angular (11.0.0-rc.2).
