### ISSUE TITLE
AngularFireModule is required while Unit testing ?

### ISSUE THREAD

**Issue by sivanshkamat** [angular/angularfire#3382] opened 2023-06-15 08:54 UTC
I am trying to unit test my angular project where I added firebase for authentication and realtime database.
The project runs with no error but while unit testing: i get following error:
image

Here, I have created a Authentication service for required signup, login and logout functions:

`import { Injectable } from '@angular/core';
import { from, Observable,} from 'rxjs';
import {
Auth,
signInWithEmailAndPassword,
authState,
createUserWithEmailAndPassword,
UserCredential,
} from '@angular/fire/auth';

@Injectable({
providedIn: 'root',
})
export class AuthService {
currentUser$ = authState(this.auth);

signUp(email: string, password: string): Observable {
return from(createUserWithEmailAndPassword(this.auth, email, password));
}

login(email: any, password: any): Observable {
return from(signInWithEmailAndPassword(this.auth, email, password));
}

logout(): Observable {
return from(this.auth.signOut());
} constructor(public auth: Auth) {}

}
`
Please keep me posted.

Versions info:
@angular/fire : 7.6.1
@angular-devkit/build-angular: 16.0.1
@angular/cli: 16.0.1

**Comment by davideast** [comment] 2023-06-22 18:13
Duplicate of #3383

**Closed by davideast** 2023-06-22 18:13 UTC
