### ISSUE TITLE
Error in complilation ERROR in node_modules/@angular/fire/firebase.app.module.d.ts:2:10 - error TS2614

### ISSUE THREAD

**Issue by rogerbobbio** [angular/angularfire#2622] opened 2020-10-27 22:06 UTC
Hi, Please help me with the folllowing compiling issue:

I have installed :

+ angularfire2@5.4.2
+ firebase@8.0.0

My project have the following dependencies:

"@angular/animations": "^10.0.14",
    "@angular/cdk": "^10.2.2",
    "@angular/common": "~10.0.2",
    "@angular/compiler": "~10.0.2",
    "@angular/core": "~10.0.2",
    "@angular/forms": "~10.0.2",
    "@angular/material": "^10.2.2",
    "@angular/platform-browser": "~10.0.2",
    "@angular/platform-browser-dynamic": "~10.0.2",
    "@angular/router": "~10.0.2",
    "angularfire2": "^5.4.2",
    "chart.js": "^2.9.3",
    "firebase": "^8.0.0",
    "ng2-charts": "^2.4.1",
    "ngx-pagination": "^5.0.0",
    "rxjs": "~6.5.5",
    "sweetalert2": "^9.17.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"

### Compilation output

ERROR in node_modules/@angular/fire/firebase.app.module.d.ts:2:10 - error TS2614: Module '"../../firebase"' has no exported member 'auth'. Did you mean to use 'import auth from "../../firebase"' instead?

    2 import { auth, database, messaging, storage, firestore, functions } from 'firebase/app';
               ~~~~
    node_modules/@angular/fire/firebase.app.module.d.ts:2:16 - error TS2614: Module '"../../firebase"' has no exported member 'database'. Did you mean to use 'import database from "../../firebase"' instead?

    2 import { auth, database, messaging, storage, firestore, functions } from 'firebase/app';
                     ~~~~~~~~
    node_modules/@angular/fire/firebase.app.module.d.ts:2:26 - error TS2614: Module '"../../firebase"' has no exported member 'messaging'. Did you mean to use 'import messaging from "../../firebase"' instead?

    2 import { auth, database, messaging, storage, firestore, functions } from 'firebase/app';
                               ~~~~~~~~~
    node_modules/@angular/fire/firebase.app.module.d.ts:2:37 - error TS2614: Module '"../../firebase"' has no exported member 'storage'. Did you mean to use 'import storage from "../../firebase"' instead?

    2 import { auth, database, messaging, storage, firestore, functions } from 'firebase/app';
                                          ~~~~~~~
    node_modules/@angular/fire/firebase.app.module.d.ts:2:46 - error TS2614: Module '"../../firebase"' has no exported member 'firestore'. Did you mean to use 'import firestore from "../../firebase"' instead?

    2 import { auth, database, messaging, storage, firestore, functions } from 'firebase/app';
                                                   ~~~~~~~~~
    node_modules/@angular/fire/firebase.app.module.d.ts:2:57 - error TS2614: Module '"../../firebase"' has no exported member 'functions'. Did you mean to use 'import functions from "../../firebase"' instead?

    2 import { auth, database, messaging, storage, firestore, functions } from 'firebase/app';
                                                              ~~~~~~~~~
    node_modules/@angular/fire/storage/interfaces.d.ts:1:10 - error TS2614: Module '"../../../firebase"' has no exported member 'storage'. Did you mean to use 'import storage from "../../../firebase"' instead?

    1 import { storage } from 'firebase/app';
               ~~~~~~~
    node_modules/@angular/fire/storage/observable/fromTask.d.ts:3:10 - error TS2614: Module '"../../../../firebase"' has no exported member 'storage'. Did you mean to use 'import storage from "../../../../firebase"' instead?

    3 import { storage } from 'firebase/app';
               ~~~~~~~
    node_modules/@angular/fire/database/interfaces.d.ts:2:10 - error TS2614: Module '"../../../firebase"' has no exported member 'database'. Did you mean to use 'import database from "../../../firebase"' instead?

    2 import { database } from 'firebase/app';
               ~~~~~~~~


![image](https://user-images.githubusercontent.com/11222817/97367226-bfeb2b80-1876-11eb-99f3-1ad3ac79304c.png)

**Comment by ingrocha** [comment] 2020-10-27 22:07
Same here!

**Comment by xylo04** [comment] 2020-10-27 22:24
This is a duplicate of #2619.

**Comment by devsandro** [comment] 2020-10-28 04:16
Same issue here

**Comment by Puthxii** [comment] 2020-10-28 09:21
Same here

**Comment by KingDarBoja** [comment] 2020-10-28 13:33
Please use latest version of Firebase v7 instead of v8 as angularfire is not compatible yet. A pull request has been made addressing this update at #2620.

**Comment by rogerbobbio** [comment] 2020-10-28 13:57
Thanks KingDarBoja is working 

People use : npm install firebase@7.24.0 angularfire2 --save

**Comment by sarunint** [comment] 2020-10-28 15:54
> Thanks KingDarBoja is working
> 
> People use : npm install firebase@7.24.0 angularfire2 --save

@rogerbobbio Protip: `angularfire2` is now `@angular/fire`. :D

**Comment by jamesdaniels** [comment] 2020-10-29 22:46
Closing in favor of #2619

**Closed by jamesdaniels** 2020-10-29 22:46 UTC

**Comment by jordankkk** [comment] 2020-11-01 02:00
updated with latest version seem still same 

**Angular:**
10.2.1

**Firebase:**
8.0.0

**AngularFire:**
6.0.4

```bash
"export 'auth' was not found in 'firebase/app'
"export 'auth' was not found in 'firebase/app'
"export 'firestore' was not found in 'firebase/app'
```

**Comment by KingDarBoja** [comment] 2020-11-01 15:30
With the new version, now you need to export `firebase/app` as follows:

```ts
import firebase from 'firebase/app';

  login() {
    this.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider());
  }
```

**Comment by sleepinzombie** [comment] 2020-11-04 17:57
I still have the issue with the latest Angular Fire and Firebase.

**Angular:**
10.2.1

**Firebase:**
8.0.0

**AngularFire:**
6.0.4

PFA the screenshot of the error while serving my app:

<img width="1019" alt="Screenshot 2020-11-04 at 9 56 45 PM" src="https://user-images.githubusercontent.com/39788411/98150811-a8e8b100-1ee8-11eb-9f10-8a8f3e830d98.png">

**Comment by sarunint** [comment] 2020-11-05 14:50
> I still have the issue with the latest Angular Fire and Firebase.
> 
> **Angular:**
> 10.2.1
> 
> **Firebase:**
> 8.0.0
> 
> **AngularFire:**
> 6.0.4
> 
> PFA the screenshot of the error while serving my app:
> 
> <img alt="Screenshot 2020-11-04 at 9 56 45 PM" width="1019" src="https://user-images.githubusercontent.com/39788411/98150811-a8e8b100-1ee8-11eb-9f10-8a8f3e830d98.png">

Are you sure that is AngularFire 6.0.4? Seems like 6.0.3 for me.

Did you forget to `npm install`?

**Comment by sleepinzombie** [comment] 2020-11-05 15:21
@sarunint Actually I managed to solve the issue I was having. My Node was v15. I downgraded to v14 and everything served fine.

**Comment by inbatamilan-573** [comment] 2020-11-06 10:56
same here

**Comment by gabriel-arrvda** [comment] 2020-11-10 01:37
I still have the issue using the 6.04v of the Angular Fire and 7v of Firebase

![image](https://user-images.githubusercontent.com/73544831/98616444-918c3800-22db-11eb-8302-88da4329122f.png)

**Comment by KingDarBoja** [comment] 2020-11-10 14:39
You need to install firebase v8, not v7, take a look at the compatibility table at https://github.com/angular/angularfire#compatibility

**Comment by Awais-mohammad** [comment] 2020-11-17 05:35
Hello peoples please use version 7 instead of 8 use this npm command and it will work i was also shocked when i got this error but thans to @rogerbobbio  and @KingDarBoja 
 npm install firebase@7.24.0 angularfire2 --save

**Comment by JefferE** [comment] 2020-11-19 19:51
This is actually the correct install until this is resolved with new @angularfire:

`npm install firebase@7.24.0 @angular/fire@6.0.3 --save`

Otherwise 6.0.4 is installed by default and that's broken

**Comment by Awais-mohammad** [comment] 2020-11-20 01:06
@JefferE
I used this and it worked fine with ionic 4 and angular 8
 npm install firebase@7.24.0 angularfire2 --save

**Comment by pkmuduli001** [comment] 2020-11-25 10:30
though it gives some warning but it will solve the issue, try this 
npm install firebase@7.24.0 @angular/fire@6.0.3 --save

**Comment by Chandra1996** [comment] 2021-07-23 15:23
i m still getting the error

**Comment by Awais-mohammad** [comment] 2021-07-23 15:25
@Chandra1996 the issue is just due to firebase version uninstall previous version remove it from angular.json then reinstall 7.24.0 version nd ng serve again

**Comment by yuvagp** [comment] 2022-04-29 03:41
Hi 
 I am getting the following error when I try to update my anuglar 12 project to angular13 and firebase to 7
/node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:597:29-40 - Error: export 'SDK_VERSION' (imported as 'SDK_VERSION') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:784:19-31 - Error: export '_getProvider' (imported as '_getProvider') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:3030:6-17 - Error: export 'SDK_VERSION' (imported as 'SDK_VERSION') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12058:7-18 - Error: export 'SDK_VERSION' (imported as 'SDK_VERSION') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12282:7-18 - Error: export 'SDK_VERSION' (imported as 'SDK_VERSION') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12736:2-20 - Error: export '_registerComponent' (imported as '_registerComponent') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12803:2-20 - Error: 0mexport '_registerComponent' (imported as '_registerComponent') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12817:2-17 - Error: export 'registerVersion' (imported as 'registerVersion') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12819:2-17 - Error: export 'registerVersion' (imported as 'registerVersion') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12848:23-29 - Error: export 'getApp' (imported as 'getApp') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/auth-compat/node_modules/@firebase/auth/dist/esm2017/index-7078a255.js:12849:19-31 - Error: export '_getProvider' (imported as '_getProvider') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/database-compat/node_modules/@firebase/database/dist/index.esm2017.js:15528:27-33 - Error: export 'getApp' (imported as 'getApp') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/database-compat/node_modules/@firebase/database/dist/index.esm2017.js:15529:9-21 - Error: export '_getProvider' (imported as '_getProvider') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

./node_modules/@firebase/database-compat/node_modules/@firebase/database/dist/index.esm2017.js:15645:16-29 - Error: export 'SDK_VERSION' (imported as 'SDK_VERSION$1') was not found in '@firebase/app' (possible exports: __esModule, default, firebase)

pls help

**Comment by Hulliee** [comment] 2022-06-02 15:45
> This package.json should work:
> 
> "dependencies": { "@angular/animations": "~13.2.0", "@angular/common": "~13.2.0", "@angular/compiler": "~13.2.0", "@angular/core": "~13.2.0", "@angular/fire": "^7.2.1", "@angular/forms": "~13.2.0", "@angular/platform-browser": "~13.2.0", "@angular/platform-browser-dynamic": "~13.2.0", "@angular/router": "~13.2.0", "bootstrap": "^5.1.3", "firebase": "^9.6.7", "rxjs": "~7.5.0", "tslib": "^2.3.0", "zone.js": "~0.11.4" }, "devDependencies": { "@angular-devkit/build-angular": "~13.2.3", "@angular/cli": "~13.2.3", "@angular/compiler-cli": "~13.2.0", "@types/jasmine": "~3.10.0", "@types/node": "^12.11.1", "jasmine-core": "~4.0.0", "karma": "~6.3.0", "karma-chrome-launcher": "~3.1.0", "karma-coverage": "~2.1.0", "karma-jasmine": "~4.0.0", "karma-jasmine-html-reporter": "~1.7.0", "typescript": "~4.5.2" }

Thank you! This works well with Angular 13

**Comment by tayoraph** [comment] 2022-06-19 13:01
> This package.json should work:
> 
> "dependencies": { "@angular/animations": "~13.2.0", "@angular/common": "~13.2.0", "@angular/compiler": "~13.2.0", "@angular/core": "~13.2.0", "@angular/fire": "^7.2.1", "@angular/forms": "~13.2.0", "@angular/platform-browser": "~13.2.0", "@angular/platform-browser-dynamic": "~13.2.0", "@angular/router": "~13.2.0", "bootstrap": "^5.1.3", "firebase": "^9.6.7", "rxjs": "~7.5.0", "tslib": "^2.3.0", "zone.js": "~0.11.4" }, "devDependencies": { "@angular-devkit/build-angular": "~13.2.3", "@angular/cli": "~13.2.3", "@angular/compiler-cli": "~13.2.0", "@types/jasmine": "~3.10.0", "@types/node": "^12.11.1", "jasmine-core": "~4.0.0", "karma": "~6.3.0", "karma-chrome-launcher": "~3.1.0", "karma-coverage": "~2.1.0", "karma-jasmine": "~4.0.0", "karma-jasmine-html-reporter": "~1.7.0", "typescript": "~4.5.2" }

_This works for angular 14_

**Comment by agungss** [comment] 2022-09-07 17:37
> This package.json should work:
> 
> "dependencies": { "@angular/animations": "~13.2.0", "@angular/common": "~13.2.0", "@angular/compiler": "~13.2.0", "@angular/core": "~13.2.0", "@angular/fire": "^7.2.1", "@angular/forms": "~13.2.0", "@angular/platform-browser": "~13.2.0", "@angular/platform-browser-dynamic": "~13.2.0", "@angular/router": "~13.2.0", "bootstrap": "^5.1.3", "firebase": "^9.6.7", "rxjs": "~7.5.0", "tslib": "^2.3.0", "zone.js": "~0.11.4" }, "devDependencies": { "@angular-devkit/build-angular": "~13.2.3", "@angular/cli": "~13.2.3", "@angular/compiler-cli": "~13.2.0", "@types/jasmine": "~3.10.0", "@types/node": "^12.11.1", "jasmine-core": "~4.0.0", "karma": "~6.3.0", "karma-chrome-launcher": "~3.1.0", "karma-coverage": "~2.1.0", "karma-jasmine": "~4.0.0", "karma-jasmine-html-reporter": "~1.7.0", "typescript": "~4.5.2" }

This works for angular 12 too. Thanks!

**Comment by stephanietuerk** [comment] 2023-02-05 17:38
Also for Angular 15, the following is working (upgrading from 8 -> 9 solved my issue)
```
"dependencies": {
  ...other angular deps...
  "@angular/core": "^15.1.2",
  "@angular/fire": "^7.5.0",
  ...other deps...
  "firebase": "^9.17.1", // used `npm install firebase` to bring up to latest version after manually switching to 9
 }
 ``
