### ISSUE TITLE
SSR - ERROR Error: Uncaught (in promise): TypeError: app.firestore is not a function

### ISSUE THREAD

**Issue by Karman40** [angular/angularfire#2700] opened 2020-12-01 00:29 UTC
### Version info
<pre>
<code>
    "@angular/core": "^11.0.2",
    "@angular/fire": "^6.1.3",
    "@angular/platform-browser": "^11.0.2",
    "@angular/platform-browser-dynamic": "^11.0.2",
    "@angular/platform-server": "^11.0.2",
    "@nguniversal/express-engine": "^11.0.0",
    "firebase": "^8.1.1",
    "express": "^4.15.2",
</code>
</pre>

### Debug output

** Errors in the JavaScript console **

<pre><code>
ERROR Error: Uncaught (in promise): TypeError: app.firestore is not a function
TypeError: app.firestore is not a function
    at D:\Angular\konigs-art\dist\server\main.js:1:708430
    at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:2399970)
    at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:2392384)
    at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:2934167)
    at D:\Angular\konigs-art\dist\server\main.js:1:708404
    at ɵfetchInstance (D:\Angular\konigs-art\dist\server\main.js:1:3654610)
    at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:708332)
    at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:709945)
    at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:2700696)
    at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:2697715)
    at resolvePromise (D:\Angular\konigs-art\dist\server\main.js:1:2410283)
    at resolvePromise (D:\Angular\konigs-art\dist\server\main.js:1:2409224)
    at D:\Angular\konigs-art\dist\server\main.js:1:2411874
    at ZoneDelegate.invokeTask (D:\Angular\konigs-art\dist\server\main.js:1:2400902)
    at Object.onInvokeTask (D:\Angular\konigs-art\dist\server\main.js:1:2932615)
    at ZoneDelegate.invokeTask (D:\Angular\konigs-art\dist\server\main.js:1:2400792)
    at Zone.runTask (D:\Angular\konigs-art\dist\server\main.js:1:2393467)
    at drainMicroTaskQueue (D:\Angular\konigs-art\dist\server\main.js:1:2404510) {
  rejection: TypeError: app.firestore is not a function
      at D:\Angular\konigs-art\dist\server\main.js:1:708430
      at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:2399970)
      at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:2392384)
      at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:2934167)
      at D:\Angular\konigs-art\dist\server\main.js:1:708404
      at ɵfetchInstance (D:\Angular\konigs-art\dist\server\main.js:1:3654610)
      at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:708332)
      at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:709945)
      at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:2700696)
      at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:2697715),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: TypeError: app.firestore is not a function
        at D:\Angular\konigs-art\dist\server\main.js:1:708430
        at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:2399970)
        at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:2392384)
        at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:2934167)
        at D:\Angular\konigs-art\dist\server\main.js:1:708404
        at ɵfetchInstance (D:\Angular\konigs-art\dist\server\main.js:1:3654610)
        at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:708332)
        at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:709945)
        at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:2700696)
        at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:2697715)
  },
  zone: <ref *1> Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true, maybeDelayChangeDetection: false },
    _zoneDelegate: <ref *2> ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular *1],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular *1],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular *1],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular *1],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular *1],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular *1],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular *2],
      _hasTaskCurrZone: [Circular *1]
    }
  },
  task: ZoneTask {
    _zone: <ref *1> Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: TypeError: app.firestore is not a function
          at D:\Angular\konigs-art\dist\server\main.js:1:708430
          at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:2399970)
          at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:2392384)
          at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:2934167)
          at D:\Angular\konigs-art\dist\server\main.js:1:708404
          at ɵfetchInstance (D:\Angular\konigs-art\dist\server\main.js:1:3654610)
          at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:708332)
          at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:709945)
          at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:2700696)
          at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:2697715)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function (anonymous)],
    invoke: [Function (anonymous)]
  }
}
</code></pre>

### angular.json - server build
.. config
<pre>
<code>
            "externalDependencies": [
              "@firebase/firestore",
            ]
</code>
</pre>

**Comment by jamesdaniels** [comment] 2020-12-01 01:41
Try dropping `@firebase/firestore` from external dependencies and copying over the protos in a build step or using a web-pack work-around like I have a in the sample. [See my comment here](https://github.com/angular/angularfire/issues/2686#issuecomment-733144234).

Closing as duplicate of #2686

**Closed by jamesdaniels** 2020-12-01 01:41 UTC

**Comment by Karman40** [comment] 2020-12-01 02:03
Ok i test it, thank for your help 💯 👍 !!
